### PR TITLE
Added MetaDataArgument

### PR DESCRIPTION
**Pull request by JKamsker**

### CODE REVIEW

**Comment by rosenbjerg** [comment]
Looks good. All that is missing is a unit to verify that everything is working as intended, and to protect the feature against breaking in the future by mistake of some one 👍

**Comment by JKamsker** [comment]
Added unit tests @rosenbjerg

**Comment by rosenbjerg** [comment]
Aweome! Thanks for another contribution :)

**Comment by rosenbjerg** [comment]
Also included in v.4.7.0 🚀 
Btw you are using several names in git, one of them being Weirdo, which confused me a bit when creating the change log 🤣 
image

**Comment by JKamsker** [comment]
Idk, strange :D
Thanks for the hint, gotta review my git settings 🙈

**Pull request merged**
