### PR TITLE
Fixes long path issue in unix systems

### PR DESCRIPTION
**Pull request by mii9000**
#116

### CODE REVIEW

**Comment by rosenbjerg** [comment]
Looks good, merged. Thank you :)

**Comment by mii9000** [comment]
Thanks @rosenbjerg 
Would it be possible to label it as `hacktoberfest-accepted` please

**Comment by rosenbjerg** [comment]
I think as long as the PR isn't tagged as spam, it will count towards your 5 PRs :)

**Comment by mii9000** [comment]
@rosenbjerg unfortunately, according to the new rules the limit is 4 PRs and either the repo has to be labeled as `hacktoberfest` or PRs as `hacktoberfest-accepted`. Sorry for the inconvenience.

**Comment by Xantios** [comment]
As stated in the original issue, im a total noob regarding C# but i do learn as i go.
Is there a way to pull the master version in through nuget? or do i have to wait for this version to be released ?

Also @Ibrahim-Islam Thanks for fixing this issue! :-)

**Review by xancenl — COMMENTED** [review]
The fix will not cover the problem with temp folders which can be multiple levels deep with long names in it. The only fix is to remove the GetTempPath(). And it made no sense to shorten the GUID which destroys it uniqueness. Without the use of GetTempPath() the name will fit within the character limit. Please add or update your tests which involves these code changes.

**Comment by xancenl** [comment]
> Is there a way to pull the master version in through nuget? or do i have to wait for this version to be released ?

Clone the master repository to your local solution and add it as reference to target project.

**Comment by rosenbjerg** [comment]
@xancenl I can definitely follow your point. Do you have a suggestion to an alternative?

**Comment by zhynroman** [comment]
Hi guys, I just wanted to check whether this fix be released eventually or not?

**Pull request merged**
