### PR TITLE
Subtitle hardburning tests (ignore will be deleted)

### PR DESCRIPTION
**Pull request by alex6dj**
A test to check how to correctly implement subtitle hardburning tests in github.

In windows a fonts.config file is needed for correct subtitle hardburning, but I must check if it is detected, because if it don't exist or is not detected the conversion ends without error, only with some info in the output window.

In linux it should run without any problem.

### CODE REVIEW

**Comment by alex6dj** [comment]
Seems that this test enviroment don't need extra work for subtitle hardburning tests. I can't check if the output video really contains the subtitle but at least the executed command can be checked.

**Comment by keke1210** [comment]
@alex6dj I have issues when I deploy on windows: 
[Parsed_subtitles_0 @ 0000023cfde38ec0] fontselect: failed to find any fallback with glyph 0x0 for font: (Arial, 400, 0)

Will adding a fonts.config fix the issue?

**Comment by alex6dj** [comment]
Has been a long time.

@keke1210 Maybe, I thinks it depends of the ffmpeg binary you are using, I had lot of troubles with subtitles in the past with Windows. Using a fonts.config with the ffmpeg binaries always solve the problem. I attached the config I'm using 

[fonts.zip](https://github.com/rosenbjerg/FFMpegCore/files/14129725/fonts.zip)

**Comment by keke1210** [comment]
Thanks @alex6dj ! Also could you please tell me what else to keep in mind? and also where do you downloaded your ffmpeg binaries? Did you do some extra configurations? etc... 
I am trying to make this work on a Windows Azure function using this code: 

```csharp
await FFMpegArguments
             .FromFileInput(videoInputPath, true)
             .AddFileInput(audioPath, true)
             .OutputToFile(videoOutputPath, true, (options) =>
             {
                 options
                    .WithDuration(totalAudioDuration)
                    .WithVideoFilters((videoOptions) =>
                    {
                        videoOptions.HardBurnSubtitle(SubtitleHardBurnOptions.Create(subtitlesFile));
                    });
             })
             .ProcessAsynchronously()
```

**Comment by alex6dj** [comment]
In order to hardcode subtitles, your ffmpeg version needs to be compiled with libass support. Now Im not working with ffmpeg. I used to build it my self but now use https://www.gyan.dev/ffmpeg/builds/ binaries, you can make an script to download the latest version when needed. No extra config except for fonts.config

**Comment by keke1210** [comment]
@alex6dj What if I need to use a custom Font like Monserrat for example? Have you done that before?

**Comment by alex6dj** [comment]
Not really, I just use Arial, but should work.

**Pull request closed without merging**
