### PR TITLE
HDR10-Metadata

### PR DESCRIPTION
**Pull request by centuryx476**
Added ColorSpace, ColorPrimaries, ColorTransfer
I cannot figure out how to add "side_data_list" which is crucial for HDR10 metadata. But at least this is a start to getting HDR10 metadata.

Issue I made: https://github.com/rosenbjerg/FFMpegCore/issues/216

### CODE REVIEW

**Comment by rosenbjerg** [comment]
Looks good, but I don't see any tests demonstrating that it actually works? :)

**Comment by centuryx476** [comment]
Oops, 
I didn't make a unit test but I kept a screenshot of FFMpegCore grabbing the HDR color values
HDR Color Info

**Comment by rosenbjerg** [comment]
@centuryx476 All this needs is one or two unit tests. The implementation looks fine 
Could you add one or two tests verifying that the feature works as intended. It makes it much easier keep the code healthy if we have good test coverage

**Comment by rosenbjerg** [comment]
A single unit test has been added, but a HDR10 video file for the test is still missing. The file should be as short as possible, maybe 3 seconds, to avoid the test(s) being slow and the git repo getting any heavier

@centuryx476 Do you have an HDR10 video file that you can create a short clip from, for this purpose? If so, please share it in a comment on this thread if possible, or add it in a PR

I would like to get this PR merged, but I really prefer that new functionality is covered by one or more unit tests, to ensure the behaviour is correct and that the feature isn't broken without anyone realising, in the future

**Comment by centuryx476** [comment]
@rosenbjerg I have a short HDR clip I can share. 
How do I pass it along ?

**Comment by rosenbjerg** [comment]
@centuryx476 I think media files can be attached to comments here. Not sure about which file extensions and formats that are supported though. If it is small already, you can just add it to this PR in the test resources folder. If it is a big file, you can shorten the video to a few seconds to bring down the size :)

**Pull request closed without merging**
