### PR TITLE
#90 Fixed openning of console window and added debug output of ffmpeg…

### PR DESCRIPTION
**Pull request by max619**
#90

### CODE REVIEW

**Comment by rosenbjerg** [comment]
I'm not sure what the purpose of this change is, could you explain it a bit? :)

**Comment by max619** [comment]
When starting new instance of ffmpeg process we need to define `CreateNoWindow=true` to suppress poping up console window. `UseShellExecute=true` to attach ffmpeg process to process from wrapper is used. If parent process is crashed, child process will be closed automaticly. And writing ffmpeg output to debug just for ease of development purposes

**Comment by rosenbjerg** [comment]
Dont we need `UseShellExecute=false` to redirect I/O of the process? That is also what you have committed btw.
I have never had a console window open when running tests or using the library for analysing or converting. Have you?

**Comment by max619** [comment]
Yeah, my bad, i meant `UseShellExecute=false`.

Console window never pops up when running tests, because VS supresses it. But when running from other application it appears.

I made a little project to reproduce it. Take a look at [it](https://gofile.io/d/MKFVIW). `TestAppFfmpeg\bin\Debug\netcoreapp3.1` build with my changes. `TestAppFfmpeg\bin\Debug\netcoreapp3.1_old` build with nuget version

**Comment by rosenbjerg** [comment]
Even when using FFMpegCore in projects running in my IDE (not unit tests), I've never seen a console open.
But if you are able to replicate the problem, I believe it is a problem

**Comment by rosenbjerg** [comment]
I have updated the depency for Instances to v1.6, which sets CreateNoWindow to true.
I have also added Debug.WriteLine(..) in the event handler for debugging purposes.
Which of the changes would still be necessary?

**Comment by techartdev** [comment]
I was about to ask is that supported and just saw there is a PR. Checked and saw that it's exactly for the ffmpeg window. So yes, a window appears. I'm using it in a WPF app, .NET 4.7.1. Will temporary fix it locally until this reaches the next release.

**Comment by rosenbjerg** [comment]
@vankyy26 Thanks for reporting that. I haven't experienced that myself, so I was surprised to hear that was a problem.
I'll release a new version of the library, with CreateNoWindow set to true, as soon as a I hear from @max619

**Comment by rosenbjerg** [comment]
Closing this pull request without merge, because (hopefully) all the improvements have been incorporated into the current codebase, though in a slighty different manner.
Thank you @max619 for pinpointing these issues

**Pull request closed without merging**
