### PR TITLE
Fixed error when burning subtitle with some special charaters in path

### LINKED ISSUE #259: Error when hardburning subtitles with specials characters in path
Seems that i forgot, when implementing hardburning, that some characters must be escaped before pass subtitle path to ffmpeg subtitle filter.

### PR DESCRIPTION
**Pull request by alex6dj**
Closes #259

### CODE REVIEW

**Comment by alex6dj** [comment]
Still needs to implement single quote escaping

**Comment by alex6dj** [comment]
I didn't found a way to implement a real life subtitle hardburning conversion test. Because in windows it need a fonts folder side by side with ffmpeg executable and several other files in it for this to work. And in linux I not really sure what needs.

**Comment by alex6dj** [comment]
Single quotes fixed. I think this PR is finished now, but we need some real test to be sure that the conversion with subtitles really work. I tested locally and runs ok (windows) but I don't know how to set all prerequisites in github. So I'll leave it for you as homework  ;)

**Comment by rosenbjerg** [comment]
Thanks again alex6dj

**Pull request merged**
