### PR TITLE
Add InputDeviceArgument

### PR DESCRIPTION
**Pull request by TFleury**
Allow device input, such as capture cards, webcams or desktop capture.

## Sample usage :
DirectShow
```cs
FFMpegArguments.FromDeviceInput("video=\"Camera\":audio=\"Microphone\"", args => 
    args.ForceFormat("dshow"))
```

### CODE REVIEW

**Comment by rosenbjerg** [comment]
Do you think it would make sense to add overload method that takes VideoInputDevice and AudioInputDevice enum members?

**Comment by TFleury** [comment]
I'm not sure to understand your question. Could you provide an example of what you have in mind ?

**Comment by rosenbjerg** [comment]
Yeah sure
```csharp
enum VideoInputDevice { Camera, ... }
enum AudioInputDevice { Microphone, ... }

FFMpegArguments
    .FromDeviceInput(VideoInputDevice.Camera, AudioInputDevice.Microphone, options=> options
        .ForceFormat("dshow"))
    ...
```
But that would only really make sense if there are multiple enum members in each, and the device naming isn't dependent on the hardware, which I suspect it might be for several device types

**Comment by TFleury** [comment]
`video="Camera":audio="Microphone"` notation is specific to `dshow` filter, and "Camera" and "Microphone" are not real values.
Each device have a different name, based on model and manufacturer, so we can't use an enum.

Here is the dedicated documentation : [FFmpeg Devices Documentation](https://ffmpeg.org/ffmpeg-devices.html)
There are different notations based which filter is used.

Maybe we can add the `ForceFormat` argument into the extension method, to have something like this :
```cs
FFMpegArguments.FromDeviceInput("dshow", "video=\"Camera\":audio=\"Microphone\"")
```

**Comment by nikeee** [comment]
I'm capturing the screen using this prototype code:

```csharp
class OffsetArgument : IArgument
{
    private readonly int _offset;
    private readonly string _dimension;
    public OffsetArgument(int offset, string dimension)
    {
        _offset = offset;
        _dimension = dimension;
    }
    public string Text => $"-offset_{_dimension.ToLowerInvariant()} {_offset}";
}

class VideoSizeArgument : IArgument
{
    private readonly int _x;
    private readonly int _y;
    public VideoSizeArgument(int x, int y)
    {
        _x = x;
        _y = y;
    }
    public string Text => $"-video_size {_x}x{_y}";
}

class ShowRegionArgument : IArgument
{
    private readonly int _value;
    public ShowRegionArgument(int value) => _value = value;
    public string Text => $"-show_region {_value}";
}

// ....

var format = formats.FirstOrDefault(e => e.Name == "gdigrab");

// ffmpeg -f gdigrab -framerate 30 -offset_x 10 -offset_y 20 -video_size 640x480 -show_region 1 -i desktop output.mkv
var instance = FFMpegArguments.FromFileInput("desktop", false, options => options
    .ForceFormat(format)
    .WithFramerate(30)
    .WithArgument(new OffsetArgument(10, "x"))
    .WithArgument(new OffsetArgument(20, "y"))
    .WithArgument(new VideoSizeArgument(640, 480))
    .WithArgument(new ShowRegionArgument(1))
).OutputToFile(@"test.mp4");

instance.CancellableThrough(out var cancelCapture);
_ = instance.ProcessAsynchronously();

await Task.Delay(5000);
cancelCapture();
```

Despite the `OffsetArgument` class being a bit hacky (maybe the dimension sould be an enum or we should use two separate classes), this works. Maybe using `record`s would make more sense.

Is it something that you'd merge or should these kind of arguments be implemented on the application level?

**Pull request merged**
