### PR TITLE
Fix parse TimeSpan  and get main duration

### PR DESCRIPTION
**Pull request by HmarikBel**

### CODE REVIEW

**Comment by rosenbjerg** [comment]
What is the purpose of this PR? I do not understand it from the code changes, and you haven't written what the problem was. 
Why does TimeSpan parsing need fixing, and what is main duration and why is it read from ErrorData

**Comment by rosenbjerg** [comment]
Did FFProbe actually output a duration with more than 7 fractions of a second precision?

**Comment by HmarikBel** [comment]
I have a file example. There is no duration in a stream data, but there is a TAG like this "00:00:21.163000000".
And I have a couple of examples with no duration in data and no tags (*.webm).
I don't know why, but Instance class store first lines of FFProbe output in ErrorData. And line like this " Duration: 00:00:21.25, start: 0.000000, bitrate: 1893 kb/s"  also in ErrorData.
If it's necessary I can share my video examples (it's just random files from Internet).

**Comment by rosenbjerg** [comment]
If you could just post the ffprobe text output from OutputData and ErrorData (perhaps anonymize foldernames), I'll take a look at what's going on.

If I understand you correctly, the TAG can sometimes have more than 7 fractions. That makes sense because the TAG is just text metadata, so it isn't validated I think. So I agree that there needs to be some sort of checking/cleaning before parsing it.

But I still don't understand what main duration is for, and why it is needed.
Have you experienced that a file was analyzed without error using FFProbe.Analyse, but that no streams were found and thus no duration?

**Comment by HmarikBel** [comment]
File with TAG more then 7 fraction:

Output
{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "High",
            "codec_type": "video",
            "codec_time_base": "1/50",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 1280,
            "height": 720,
            "coded_width": 1280,
            "coded_height": 720,
            "closed_captions": 0,
            "has_b_frames": 2,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "16:9",
            "pix_fmt": "yuv420p",
            "level": 31,
            "chroma_location": "left",
            "field_order": "progressive",
            "refs": 1,
            "is_avc": "true",
            "nal_length_size": "4",
            "r_frame_rate": "25/1",
            "avg_frame_rate": "25/1",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "bits_per_raw_sample": "8",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "HANDLER_NAME": "\u001fMainconcept Video Media Handler",
                "ENCODER": "Lavc57.83.101 libx264",
                "DURATION": "00:00:21.163000000"
            }
        },
        {
            "index": 1,
            "codec_name": "vorbis",
            "codec_long_name": "Vorbis",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": 0,
            "start_time": "0.000000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            },
            "tags": {
                "language": "eng",
                "HANDLER_NAME": "#Mainconcept MP4 Sound Media Handler",
                "ENCODER": "Lavc57.83.101 libvorbis",
                "DURATION": "00:00:21.251000000"
            }
        }
    ]
}


https://github.com/prof3ssorSt3v3/media-sample-files/blob/master/lion-sample.webm

File with NO duration in streams and tags:
ErrorData
ffprobe version git-2020-06-03-b6d7c4c Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 9.3.1 (GCC) 20200523
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 49.100 / 56. 49.100
  libavcodec     58. 90.100 / 58. 90.100
  libavformat    58. 44.100 / 58. 44.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 84.100 /  7. 84.100
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
Input #0, matroska,webm, from 'd:\TestVideo\lion-sample.webm':
  Metadata:
    encoder         : Lavf57.66.105
  Duration: 00:01:56.71, start: -0.003000, bitrate: 242 kb/s
    Stream #0:0: Video: vp9 (Profile 0), yuv420p(tv, progressive), 384x288, SAR 1:1 DAR 4:3, 23.98 fps, 23.98 tbr, 1k tbn, 1k tbc (default)
    Stream #0:1: Audio: opus, 48000 Hz, mono, fltp (default)

OutputData:
{
    "streams": [
        {
            "index": 0,
            "codec_name": "vp9",
            "codec_long_name": "Google VP9",
            "profile": "Profile 0",
            "codec_type": "video",
            "codec_time_base": "1001/24000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 384,
            "height": 288,
            "coded_width": 384,
            "coded_height": 288,
            "closed_captions": 0,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "4:3",
            "pix_fmt": "yuv420p",
            "level": -99,
            "color_range": "tv",
            "chroma_location": "center",
            "field_order": "progressive",
            "refs": 1,
            "r_frame_rate": "24000/1001",
            "avg_frame_rate": "24000/1001",
            "time_base": "1/1000",
            "start_pts": 49,
            "start_time": "0.049000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        },
        {
            "index": 1,
            "codec_name": "opus",
            "codec_long_name": "Opus (Opus Interactive Audio Codec)",
            "codec_type": "audio",
            "codec_time_base": "1/48000",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "48000",
            "channels": 1,
            "channel_layout": "mono",
            "bits_per_sample": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/1000",
            "start_pts": -3,
            "start_time": "-0.003000",
            "disposition": {
                "default": 1,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0
            }
        }
    ]
}

**Comment by rosenbjerg** [comment]
As I understand it from [this](https://trac.ffmpeg.org/ticket/5020), ffprobe outputs debug info to stderr (ErrorData), while the analysis output in json is written to stdout (OutputData). 
I find it interesting the ffprobe doesn't output a duration property in the json output when it clearly has the ability to determine the duration. I'll look more into that tomorrow, and perhaps make the library parse that debug info to get the duration from there

**Comment by rosenbjerg** [comment]
I have released v.2.1 of the library, which uses a regex before parsing the TimeSpan. This should fix your issue

**Comment by HmarikBel** [comment]
Thanks, one issue gone.

**Comment by rosenbjerg** [comment]
Do you still have the issue where FFProbe doesn't find a duration, even though the debug info (ErrorData) contains one?

**Comment by HmarikBel** [comment]
Yes, I still have the issue. Please check this file
https://github.com/prof3ssorSt3v3/media-sample-files/blob/master/lion-sample.webm

**Comment by rosenbjerg** [comment]
I have release v2.2 which, in addition to the streams, also parses the format info from ffprobe containing the duration.
I have verified that it finds the duration of the lion file.

I'll close this issue now that both problems have been covered

**Pull request closed without merging**
